version: '3.8'

services:
  laravel-service:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: laravel-service-cont
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - DB_HOST=mysql-service
      - DB_DATABASE=blog-db
      - DB_USERNAME=Admin
      - DB_PASSWORD=Admin123
    networks:
      - blog-red
    depends_on:
      - mysql-service
  mysql-service:
    build: 
      context: ./db
      dockerfile: Dockerfile
    container_name: mysql-service-cont
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - blog-red
    
volumes:
  db_data:
networks:
  blog-red: