version: '3.8'

services:
  laravel-service:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: laravel-service-cont
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - DB_HOST=mysql-service
      - DB_DATABASE=db
      - DB_USERNAME=Admin
      - DB_PASSWORD=Admin123
    networks:
      - red-laradock

  mysql-service:
    image: mysql:8.0
    container_name: mysql-service-cont
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: db
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - red-laradock

volumes:
  db_data:

networks:
red-laradock:
